twig:
    form_themes: ['tailwind_2_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%site_name%'

when@test:
    twig:
        strict_variables: true
