twig:
    form_themes: ['tailwind_2_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%site_name%'
        products_path: '%products_path%'
        logo_path: '%logo_path%'

when@test:
    twig:
        strict_variables: true
