vich_uploader:
    db_driver: orm

    mappings:
       products:
            uri_prefix: '%products_path%'
            upload_destination: '%kernel.project_dir%/public/%products_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true